### ISSUE TITLE
Very slow hardware decode using Intel iGPU with VAAPI

### ISSUE THREAD

**Issue by robert-sandor** [flathub/com.parsecgaming.parsec#16]
I've tested this on two different systems (a laptop with an i7-8550U running Fedora 35 and an Intel NUC with i5 10210U with Pop OS 21.10).

On the laptop, running it through software rendering, I get ~15ms decode time, and it's very variable. If I enable the wayland socket, it switches to hardware decoding, and I get ~30ms decode time.

On the NUC, I can reproduce this, and I can also install the Parsec provided DEB. Here, same happens as on the laptop while running the flatpak, but when running the DEB directly, i get about 5-7ms decode time.

This is all for a 1080p60 stream from a LAN connected Windows host.

Is there a reason the flatpak version is so much slower with software rendering, and can that be fixed some way ?

**Comment by ajussak** [comment]
Same with Fedora. VAAPI not working with Parsec Flatpak.

I tested with others Flatpak packages (like Clapper), VAAPI is working very well.

**Comment by timmy443** [comment]
I have the same issue. In the logs I keep getting.
[I 2022-07-27 02:03:55] VAAPI: (1.7) Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
[D 2022-07-27 02:03:59] Decoder failure, queued_frames=62
Its also happening on the Parcec deb package.

Moonlight flatpak works great.

**Comment by zastrixarundell** [comment]
Parsec in itself doesn't currently support hardware decoding on Linux. They are intending to add it on the next release.

**Comment by Kodikuu** [comment]
Parsec has not directly used libva for a long time now. With the rollout of 150-94, hardware decode will be restored in the form of FFMPEG 4, 5, and 6, hardware decode
