### ISSUE TITLE
Parsec Flatpak Permission Issue

### ISSUE THREAD

**Issue by wesbluemarine** [flathub/com.parsecgaming.parsec#18]
Parsec flatpak does not start and reports the following error.

`makaba@PC192:~> flatpak run --socket=wayland com.parsecgaming.parsec
/home/makaba/parsecd-150-28.so: cannot enable executable stack as shared object requires: Permission denied`

**OS is openSUSE MicroOS**

**Comment by bi0shacker001** [comment]
Parsec doesn't support wayland. You've gotta give it X11 (and ONLY X11) permissions. This is not specific to the flatpak, Parsec itself has no support for wayland and runs in xorg-wayland.
