### ISSUE TITLE
libavcodec58 not found on your system. [-22]

### ISSUE THREAD

**Issue by rndevfx** [flathub/com.parsecgaming.parsec#23]
With the latest update from today I got an error when starting the connection to the remote OS (Windows in my case). I'm using Parsec version 150-85c.

Some discussion is here as well: https://www.reddit.com/r/ParsecGaming/comments/z6ixyx/flatpak_libavcodec58_not_found_on_your_system_22

**Comment by leohearts** [comment]
+1 I'm using Ubuntu Lunar Lobster (development branch), and libavcodec58 has been upgraded to libavcodec59 .
Consider bundling libavcodec58 within ?

**Comment by NightHammer1000** [comment]
This is down to the SDK Version used I think.
Switching back to 21.08 should fix it.

**Comment by rndevfx** [comment]
This fixed the issue for me :)

**Comment by NightHammer1000** [comment]
Even with Flatpak we cant escape dependency hell :3

**Comment by rndevfx** [comment]
Fixed
