### ISSUE TITLE
Sluggisch and Sticky Controller input when ran through Steam

### ISSUE THREAD

**Issue by NightHammer1000** [flathub/com.parsecgaming.parsec#25]
You can most noticeable see it on the Steam Deck.
Got to Settings -> Gamepad in Parsec and start pressing Buttons.
You will see that some buttons stick as pressed or do not even register as pressed at all.

I suspect this is a General Parsec Incompatibility with the Steam Input System, but I open it here anyway on the off chance that it is a Flatpak Issue.

Lets hope its a Flatpak one, the chances of getting it fixed otherwise are pretty slim.

**Comment by olegshulyakov** [comment]
The issue is still reproduced on latest version 3.9.8.

Is there any workaround for this?

**Comment by NightHammer1000** [comment]
Sadly no. I wasted weeks trying to find one.
Parsec Staff itself does not care at all. They wont even look at the Issue.

**Comment by ictnetw** [comment]
Hi, I found a workaround. In my case, I run Parsec in gaming mode on my Steam Deck. I connect an Xbox One controller and Parsec detects like if two controllers were connected. Once you connect to the remote windows host and press one of the controller buttons, it detects two controllers as well. One is working fine and the other doesn't. You have to uninstall the one that is not working fine everytime you reconnect and it is challenging to find which one it is. I hope it helps.

**Comment by NightHammer1000** [comment]
Just  use Sunshine with Moonlight.
Parsecs development seriously slowed down to a crawl and community support is non-existend sice Unity3D bought them.
