### ISSUE TITLE
Run parsec on the steam deck: libavcodec58 not found on your system

### ISSUE THREAD

**Issue by DetailsMatterM** [flathub/com.parsecgaming.parsec#26]
Hi, 
I am trying to run parsec on the steam deck and while I can start it and it finds he computer (Windows) it should connect to, I am getting this error when I press connect and then it crashes:
Flatpak libavcodec58 not found on your system. [-22]

I found this threat: 
https://github.com/flathub/com.parsecgaming.parsec/issues/23 
But I am not sure how to do this on the steam deck/ if it works at all. 
Please take a look at this, would really appreciate it!

**Comment by rndevfx** [comment]
Steam Deck is using Flatpak, so this is the same issue :) This is fixed by @NightHammer1000 in PR https://github.com/flathub/com.parsecgaming.parsec/pull/24 so hopefully it will be merged soon

**Comment by DetailsMatterM** [comment]
Thank you for your answer! After the fix, will I be able to just install it over the Discover app?

**Comment by rndevfx** [comment]
Yes, this will be an update and you can install it with Discover. Maybe @SISheogorath can have a look because I think a lot of people are affected

**Comment by SISheogorath** [comment]
In order to fix things for now, I merged the downgrade, but we have to fix this permanently with the new runtime version

**Comment by DetailsMatterM** [comment]
I checked, seems that Discover does not pull the newest build right now, I have no experience with that (sorry, new to Linux and the steam deck). 
I guess they will update eventually. Will keep you posted

**Comment by NightHammer1000** [comment]
@SISheogorath Its up to Parsec to fix this as even the Native Version fails on the newest Ubuntu Builds.

**Comment by DetailsMatterM** [comment]
Yea, I tested the version from the test-server and that works, however I can't add it to run in steam, which means you can't open it in the game mode and then it pretends that there is no controller connected :D. 
How is the process, does Parsec look at this repo?

**Comment by DetailsMatterM** [comment]
Found the discord, seems it will take a while for them to fix it. Thank you for your help! Really appreciate it
