### ISSUE TITLE
Flatpak-specific config directory mislocation

### ISSUE THREAD

**Issue by bi0shacker001** [flathub/com.parsecgaming.parsec#28]
I run on a custom app_channel and with other manual config changes.

When I give the parsec access to my ~/.parsec folder, it doesn't use the config.
When I give it access to ~, it spews an entire config directory across the root of my home folder, rather than in the subfolder it should be using.

**Comment by SISheogorath** [comment]
The persistent setting the the flatpak manifest ensures that the content of the home directory is persisted but in a flatpak environment so it doesn't mess up your home directory.

You can use `flatpak run --command=sh com.parsecgaming.parsec` and edit the config inside the flatpak environment.

**Comment by bi0shacker001** [comment]
Thank you, but I know about the persistent setting (and even if I hadn't before, that's a quick google away). That's not a solution to the problem, it's a workaround that doesn't help my use-case. 

It makes me incapable of doing configuration backups, it means that if I ever have to uninstall parsec, or if anything ever goes wrong, I have to recreate my configs. And it destandardizes the parsec installation in the flatpak from regular parsec, which means it could break other use-cases too.

I can't see enough in the repo to understand why the flatpak is broken in this way, but it's specific to the flatpak. Hence, reported.

**Comment by Kodikuu** [comment]
The behaviour is correct for the flatpak, it's not _supposed_ to have read/write access to your files.
