### ISSUE TITLE
runtime org.freedesktop.Platform branch 21.08 is end-of-life

### ISSUE THREAD

**Issue by alsoGAMER** [flathub/com.parsecgaming.parsec#37]
```
Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.parsecgaming.parsec
```
   
this includes `org.freedesktop.Platform.VAAPI.Intel`, `org.freedesktop.Platform.GL.default` and `org.freedesktop.Platform.ffmpeg-full` too

**Comment by SISheogorath** [comment]
Yep, we are looking for testers: https://github.com/flathub/com.parsecgaming.parsec/pull/36

**Comment by alsoGAMER** [comment]
For what feature do you need testing specifically? I could help on that front

**Comment by SISheogorath** [comment]
The idea is to check if things was as expected, no large(, negative) differences in FPS in the new runtime vs the old one.

What we need is some hardware test base to make sure the new runtime doesn't break in unexpected ways.

**Comment by burdickjp** [comment]
I'm getting this error with the switch to the new runtime: https://github.com/flathub/com.parsecgaming.parsec/issues/23

**Comment by SISheogorath** [comment]
So as it turned out, parsec is not built against a modern version of libavcodec and therefore will not function with more modern runtimes. For now we are stuck on 21.08

**Comment by SISheogorath** [comment]
So given the current situation it seems like 21.08 is staying a while longer.

After some investigation it seems that parsec upstream sticks with Ubuntu 18.04 a distro that is 5 years old and EOL since 2023-05-31 (unless you pay canonical for extended support): https://support.parsec.app/hc/en-us/articles/4422939258893#other_distros

https://endoflife.date/ubuntu

**Comment by Kodikuu** [comment]
Since Parsec version 150-91, Parsec will also make use of libavcodec57 and 59 (FFMPEG 3 and 5).

Parsec runs fine on Ubuntu 18.04 through to 23.04, and only fails on newer versions due to the need for support for libavcodec60 (FFMPEG 6)

**Comment by alsoGAMER** [comment]
hi there @Kodikuu, sorry for the late reply.


thank you for this insight, I'll try rebasing to a newer runtime version locally later this week and I'll update you on here!

**Comment by Kodikuu** [comment]
FFMPEG hardware is now releasing. The installer will be updated when the rollout is complete.

**Comment by rowbawts** [comment]
I don't want to bog down the issue with extraneous conversation, but have they given a timeline on the rollout of this feature? I've been waiting a very long time for hardware decoding to come back to Linux clients.

**Comment by Kodikuu** [comment]
> I don't want to bog down the issue with extraneous conversation, but have they given a timeline on the rollout of this feature? I've been waiting a very long time for hardware decoding to come back to Linux clients.

We're currently sitting at about 30%, which will not budge over the weekend. I haven't asked what the intended completion date is.

**Comment by ProjectSynchro** [comment]
There seems to have maybe been some kind of upstream change as far as the missing ffmpeg libraries go.

With version 150-94a and running runtime 23.08, I can connect to hosts and I can use hardware decoding for both h264 and h265. You may want to bump your runtime version to fix hardware encode on Linux clients.

As for how well NVENC works, I don't have an nvidia device to test, but seeing as the ffmpeg libraries are included there's no reason it shouldn't work.

**Comment by ProjectSynchro** [comment]
I have made a PR with some changes as well as a bumped freedesktop runtime here: https://github.com/flathub/com.parsecgaming.parsec/pull/58

On my end all looks like it is working, but would love to know if NVIDIA users and Intel users can also use hardware decoding.

**Comment by Kodikuu** [comment]
Runtime is updated
