### ISSUE TITLE
Could not initialize window graphics - Missing libcrypto.so.3 and libGL errors

### ISSUE THREAD

**Issue by ammunoz** [flathub/com.parsecgaming.parsec#47]
Parsec stopped launching after a recent update.
```
$ flatpak run com.parsecgaming.parsec 
[D 2023-12-11 10:36:30] log: Parsec release[release] (150-91a, Service: -1, Loader: 12)
[D 2023-12-11 10:36:30] MTY_SOLoad: libcrypto.so.3: cannot open shared object file: No such file or directory
[D 2023-12-11 10:36:30] MTY_SOLoad: 'dlopen' failed to find 'libcrypto.so.3'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[I 2023-12-11 10:36:30] unprivileged_user=1 enable_webview=0
[D 2023-12-11 10:36:30] mty_gl_ctx_create: 'glXCreateContext' failed
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  89
  Current serial number in output stream:  90
~ $ Gtk-Message: 10:36:30.287: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:36:30.288: Failed to load module "canberra-gtk-module"
```

**Comment by riomccloud** [comment]
Same happening here. Debian 12.

**Comment by SISheogorath** [comment]
Just wanted to let you know I'm a bit short on time right now and it would be greatly appreciated if someone else looks into this matter.

**Comment by Keyaku** [comment]
@SISheogorath For libcrypto.so.3:
The missing library can be found in the SDK 23.08 (the manifest uses 21.08). Bumping it to 23.08 and configuring it to keep libcrypto.so.3 should, in theory, fix that part.
I don't know the implications of this change yet. May I look into it, if I have the time?

**Comment by SISheogorath** [comment]
Please go ahead :)

**Comment by Kodikuu** [comment]
The primary issue here is the GLX failure. Parsec will still run without latest libcrypto, it's just logging that it couldn't find 3.0 (but didn't log that it failed to find 1.1).

I'm hoping a runtime update does something, but adding mesa and intel vaapi to the flatpak may have an impact too, for this _and_ hardware encode when it's rolled out.

I'll take a look some time after the 150-94 rollout

**Comment by Kodikuu** [comment]
Runtime was updated to 23.08, so I _assume_ this is no longer an issue
