### ISSUE TITLE
Controller button messy

### ISSUE THREAD

**Issue by adriancuevas99** [flathub/com.parsecgaming.parsec#52]
Hi, I recently installed the flatpak version of parsec into my fedora system using Wayland. I have read that parsec is onyl compatible with X11, in my case everything works, audio, video, keyboard and mouse but the xbox controller. I have enabled all the settings in flatseal just to test but no luck.

What happens is that in the gamepad section before connecting to a host, it detects the controller, but some triggers or button are not detected. Any idea?

I know is not the controller problem because I can use it on steam for streaming to another device, even tho i get no sound (that's another problem for another day)

**Comment by Kodikuu** [comment]
So long as the controller is showing up, it will be supported to the best of the ability of [parsec-cloud/libmatoya](https://github.com/parsec-cloud/libmatoya), which Parsec is built with.
Beyond having gamepads show up, their support isn't handled by the flatpak.
