### ISSUE TITLE
Is the flatpak dead (no longer supported)

### ISSUE THREAD

**Issue by Danathar** [flathub/com.parsecgaming.parsec#53]
Just thought i'd ask since it's still in flathub but hasn't been updated in like...forever.

**Comment by SISheogorath** [comment]
Yes, this flatpak is not in good shape. I've been checking in the flatpak matrix channel for someone to take over maintainership, but there is currently no process to find new maintainers beyond "just let us know when someone wants to pick it up".

I stopped using parsec a while ago. Maybe someone who is more active wants to pick things up.

**Comment by AnicetusCer** [comment]
I wanted to get parsec workin on steam deck but it's not possible via flatpack, the manifest size it out of whack with the extra package sizes all users get is this error:

Peeps can't even try out an old version. 

Error: Wrong size for extra data https://builds.parsecgaming.com/package/parsec-linux.deb
error: Failed to install com.parsecgaming.parsec: Wrong size for extra data https://builds.parsecgaming.com/package/parsec-linux.deb

**Comment by Kodikuu** [comment]
The most recent build failed due to a server-side error with flathub https://buildbot.flathub.org/#/builders/6/builds/110470

**Comment by DriftingShadows** [comment]
> The most recent build failed due to a server-side error with flathub https://buildbot.flathub.org/#/builders/6/builds/110470

any way for us to resolve this?

**Comment by FlynnD273** [comment]
For now, you can clone the repo and build it locally using flatpak-builder. https://docs.flatpak.org/en/latest/first-build.html

This doesn't fix Flathub's issue, but you'll at least be able to install the latest build.

**Comment by SISheogorath** [comment]
I just triggered a new build today. I can't really test it these days, so if this already fixed the problem, thats' great, otherwise someone needs to dig into this.

**Comment by Kodikuu** [comment]
@SISheogorath Threw a message your way on Matrix

**Comment by Kodikuu** [comment]
Look at me, I am the maintainer now [Insert meme image here]
