### ISSUE TITLE
Latest build failed, causing flatpack install to fail.

### ISSUE THREAD

**Issue by Asharax** [flathub/com.parsecgaming.parsec#55]
Can someone restart the build for parsec flatpack so users can install from the flatpak reference? 

I believe flathub related issue was fixed on their end already, and we just need to start the build.

<img width="447" alt="Screenshot 2024-04-12 at 12 39 15" src="https://github.com/flathub/com.parsecgaming.parsec/assets/13971617/ca8a8ee0-7a35-4d7a-b6d4-42d0996c7b89">

**Comment by zachvlat** [comment]
Same here!

**Comment by hack13** [comment]
Same

**Comment by FlynnD273** [comment]
This is a temporary solution for those wishing to install the Flatpak: https://github.com/flathub/com.parsecgaming.parsec/issues/53#issuecomment-2053552935

**Comment by Asharax** [comment]
Closing the issue as the error is fixed with the rebuild.
