### ISSUE TITLE
Wayland issues

### ISSUE THREAD

**Issue by SISheogorath** [flathub/com.parsecgaming.parsec#6]
I just had to notice that the parsec desktop client reports the following error on startup:

```shell
$ flatpak run com.parsecgaming.parsec
[D 2021-01-06 19:27:24] MTY_DeleteFile: 'remove' failed with errno 39
sh: xdg-mime: command not found

[App Failure]
--------------------
Parsec could not create the application.
Please contact us if this problem persists.

```

This appears to be related to wayland, because the removal of the wayland permission and forcing parsec to use x11 solves the issue. It just results in terrible performance…

**Comment by Kodikuu** [comment]
Unless [libmatoya](https://github.com/parsec-cloud/libmatoya) gains Wayland support, I'm afraid this will continue to be an issue.
