### ISSUE TITLE
Parsec couldnt find a compatible video decoder [-10]

### ISSUE THREAD

**Issue by colelisiongaming** [flathub/com.parsecgaming.parsec#60]
On latest version 3.9.9
Get this error when decoder is set to Hardware. Software seems to work fine, any additional troubleshooting steps would be appreciated. Running on Nobara 40 Official

**Comment by Kodikuu** [comment]
It's very likely that the only available hardware decoder is Vulkan, claiming to have video support but then failing to actually execute on it. There is nothing Parsec or this Flatpak can do about this besides maybe _removing_ Vulkan as a possible decoder within Parsec.

Ideally, get vaapi working, with a valid output from `vainfo` being a good indication of that.
