### ISSUE TITLE
Not installing on Fedora 40

### ISSUE THREAD

**Issue by HamonTeacher** [flathub/com.parsecgaming.parsec#62]
Maybe it's geoblocking. Enabling VPN does not help. I tried converting to rpm - it doesn't install either.

`While downloading https://builds.parsecgaming.com/package/parsec-linux.deb: Server returned status 403`

![image](https://github.com/user-attachments/assets/92ac2a39-c802-47be-b46f-e7678a3e7e4e)

**Comment by Kodikuu** [comment]
The package is accessible just fine, and has not moved. This is not an issue with the Flatpak, but with your own internet and ability to reach and download the Parsec debian package.
